spring:
  application:
    name: "configserver"
  profiles:
    active: git
  #    active: "native"
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/hiendat04/microservices-config.git"
          default-label: "main"
          timeout: 5
          clone-on-start: true
          force-pull: true # Force the config server to pull the latest changes from the local repository on startup
#        native:
#          search-locations: "file:///Users//Admin//microservices//config"
#          search-locations: "classpath:/config"

server:
  port: 8071
